package com.pahanaedu.model;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.validation.constraints.Pattern;

public class Customer {
    private String id; // MongoDB _id field (optional, auto-generated by MongoDB)

    @NotNull(message = "Account number cannot be null")
    @Size(min = 3, max = 10, message = "Account number must be between 3 and 10 characters")
    private String accountNumber;

    @NotNull(message = "Name cannot be null")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    private String name;

    @NotNull(message = "Address cannot be null")
    @Size(min = 5, max = 200, message = "Address must be between 5 and 200 characters")
    private String address;

    @NotNull(message = "Telephone number cannot be null")
    @Pattern(regexp = "^\\+?\\d{10,15}$", message = "Telephone number must be valid (10-15 digits, optional +)")
    private String telephoneNumber;

    private double unitsConsumed; // Units consumed for billing

    // No-arg constructor for Java Beans and MongoDB
    public Customer() {
    }

    // Constructor with required fields
    public Customer(String accountNumber, String name, String address, String telephoneNumber, double unitsConsumed) {
        this.accountNumber = accountNumber;
        this.name = name;
        this.address = address;
        this.telephoneNumber = telephoneNumber;
        this.unitsConsumed = unitsConsumed;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }

    public double getUnitsConsumed() {
        return unitsConsumed;
    }

    public void setUnitsConsumed(double unitsConsumed) {
        this.unitsConsumed = unitsConsumed;
    }

    // toString for debugging and display
    @Override
    public String toString() {
        return "Customer{" +
                "id='" + id + '\'' +
                ", accountNumber='" + accountNumber + '\'' +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", telephoneNumber='" + telephoneNumber + '\'' +
                ", unitsConsumed=" + unitsConsumed +
                '}';
    }
}